name: Generate Snake

on:
  schedule: # Gera todo dia 맙 23:59
    - cron: "59 23 * * *"
  workflow_dispatch: # Permite rodar manualmente
  push:
    branches:
      - main

permissions:
  contents: write # d치 permiss칚o de escrita no reposit칩rio

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do reposit칩rio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # garante hist칩rico completo para o Snake

      - name: Gerar anima칞칚o da cobrinha 游냀
        uses: Platane/snk@v3
        with:
          github_user_name: RodrigoSantos
          outputs: dist/github-contribution-grid-snake.svg

      - name: Publicar no branch de sa칤da
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

