name: Generate Snake

on:
  schedule: # Gera todo dia √†s 23:59
    - cron: "59 23 * * *"
  workflow_dispatch: # Permite rodar manualmente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do reposit√≥rio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # garante hist√≥rico completo para o Snake

      - name: Gerar anima√ß√£o da cobrinha üêç
        uses: Platane/snk@v3
        with:
          github_user_name: Rodrigo5antos
          outputs: dist/github-contribution-grid-snake.svg

      - name: Publicar no branch de sa√≠da
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
